### ISSUE TITLE
Argentina: datos.energia.gob.ar

### ISSUE THREAD

**Issue by e2equiel** [pantherale0/pyfuelprices#15]
Hi, I don't know if this will be useful, but I share my rest yaml configuration:

```yaml
rest:
  - resource: http://datos.energia.gob.ar/api/3/action/datastore_search
    method: POST
    headers:
      Content-Type: application/json
    payload: '{"resource_id": "80ac25de-a44a-4445-9215-090cf55cfda5","q": "","filters":{"provincia": "ENTRE RIOS","localidad": "CRESPO","idproducto": "2","tipohorario": "Diurno"},"limit": 100,"offset": 0}'
    verify_ssl: false
    scan_interval: 3600
    sensor:
      - name: Shell - Nafta Super
        icon: mdi:gas-station
        unique_id: precio_nafta_super_shell
        value_template: "{{ value_json.result.records | selectattr('idempresabandera', 'eq', 4) | map(attribute='precio') | first | default }}"
        device_class: monetary
        unit_of_measurement: "ARS"
        json_attributes_path: "$.result.records[?(@.idempresabandera==4)]"
        json_attributes:
          - empresabandera
          - empresa
          - latitud
          - longitud
          - indice_tiempo
      - name: Axion - Nafta Super
        icon: mdi:gas-station
        unique_id: precio_nafta_super_axion
        value_template: "{{ value_json.result.records | selectattr('idempresabandera', 'eq', 26) | map(attribute='precio') | first | default }}"
        device_class: monetary
        unit_of_measurement: "ARS"
        json_attributes_path: "$.result.records[?(@.idempresabandera==26)]"
        json_attributes:
          - empresabandera
          - empresa
          - latitud
          - longitud
          - indice_tiempo
      - name: Puma - Nafta Super
        icon: mdi:gas-station
        unique_id: precio_nafta_super_puma
        value_template: "{{ value_json.result.records | selectattr('idempresabandera', 'eq', 28) | map(attribute='precio') | first | default }}"
        device_class: monetary
        unit_of_measurement: "ARS"
        json_attributes_path: "$.result.records[?(@.idempresabandera==28)]"
        json_attributes:
          - empresabandera
          - empresa
          - latitud
          - longitud
          - indice_tiempo
      - name: YPF - Nafta Super
        icon: mdi:gas-station
        unique_id: precio_nafta_super_ypf
        value_template: "{{ value_json.result.records | selectattr('idempresabandera', 'eq', 2) | map(attribute='precio') | first | default }}"
        device_class: monetary
        unit_of_measurement: "ARS"
        json_attributes_path: "$.result.records[?(@.idempresabandera==2)]"
        json_attributes:
          - empresabandera
          - empresa
          - latitud
          - longitud
          - indice_tiempo
```
